name: Update README with Latest Release

on:
  release:
    types: [published]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update README
        run: |
          # Fetch the latest release information
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          # Update the README file with the latest release information
          sed -i "s/latest_release_version/${LATEST_RELEASE}/g" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am "Update README with latest release: $LATEST_RELEASE"
          git push
