name: Update version and release

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - ".github/workflows/tag.yml"
      - ".github/workflows/release.yml"
      - ".goreleaser.yaml"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm install
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
