name: Go Build Test

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**/*.go'
      - '**/go.mod'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.20.4'

    - name: Build
      run: go build ./...
